### ISSUE TITLE
Unable to list/delete sessions

### ISSUE THREAD

**Issue by anthosz** [sk1418/retmux#6]
Hello,

Only the backups seems to works.

If I try to delete/list/restore a particular session by example, I have this issue:
```
retmux -l 20200402_194711
Details of backup:20200402_194711
Traceback (most recent call last):
  File "/usr/local/bin/retmux", line 4, in <module>
    __import__('pkg_resources').run_script('retmux==1.0.0', 'retmux')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/retmux-1.0.0-py2.7.egg/EGG-INFO/scripts/retmux", line 92, in <module>
    func(sys.argv[2])
  File "/usr/local/lib/python2.7/dist-packages/retmux-1.0.0-py2.7.egg/tmuxbk/controller.py", line 89, in show_and_action
    print '\n'.join(tmux.long_info())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 80-82: ordinal not in range(128)
```

If can help, you can find here my locale:
```
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
```

Best regards,

**Comment by sk1418** [comment]
@anthosz 
It is not easy to precisely locate the problem based on the information in the comment.
Several things you may want to check:

- please try to change your locale to one with utf-8 support, and try the same command again
- if changing locale doesn't help, very likely you had some special characters in your tmux window name, or you were in a directory with special characters before you backup. You can find the backup in your `~/.retmux/backup`  every screen/window was backup-ed there. Please double check the json file. 
- You can adjust the log-level in ~/.retmux/retmux.conf to have more detailed info. in ~/.retmux/retmux.log
- please upgrade to the latest version, even if it may not resolve this problem, but it contains other fix.
